### ISSUE TITLE
translate.py 실행 방법

### ISSUE THREAD

**Issue by korea7030** [kh-kim/simple-nmt#13]
안녕하세요. nmt관련해서 찾아보다가 작성하신 nmt를 사용하게 되었는데요.

모델학습은 끝났고 translate 해보려고 translate.py 명령어를 readme의 예시와 같이 입력하였고 

번역하고자 하는 입력값도 입력한 상태인데 그 다음부터 작동을 안하는것 같습니다. 

명령어는 python translate.py --model models/koth.01.10.22-27452.85.10.33-30499.12.pth --gpu_id -1 --batch_size 8 --beam_size 8 --lang koth

이런식으로 실행했구요. 한글단어든 문장이든 아무거나 입력해도 다음 step으로 안넘어가는 것 같습니다. 

제가 뭔가 잘못하고 있는 건지 확인 부탁드립니다.

**Comment by kh-kim** [comment]
안녕하세요.
해당 파일은 standard input을 입력으로 받습니다. 예를 들어 아래와 같이 실행해주면 됩니다.

python translate.py < input.txt > output.txt

또는 아래와 같은 형태도 가능합니다.

cat input.txt | python translate.py > output.txt

**Comment by korea7030** [comment]
답변 주셔서 감사합니다.
