### ISSUE TITLE
[Help Wanted] How to evaluate BLEU score on test sets

### ISSUE THREAD

**Issue by jmuntaner** [kh-kim/simple-nmt#38]
Hello, first of all thanks for making this repo public.

I'm trying to translate from DE to EN, and I've been able to train a model that does so. Now i want to evaluate the BLEU score of the model. How could I BLEU score my test set (I have test.de and test.en files)? Do I have to first translate the whole test.de and then compare to the references in test.en? How did you score your koen models?

If I'm not mistaken you seem to have scripts for that task: massive_test.py and multi-bleu.perl, but I don't really understand how to use them properly.

Thanks in advance!

**Comment by kh-kim** [comment]
Hello, @jmuntaner .

I think you need to understand the proper procedure of evaluations.
First of all, you need to detokenize hyps, if hyps are segmented by BPE.
Second, after detokenization, you need to separate different types of characters(e.g. alphabet vs period) using a tokenizer such as nltk.
After separation, finally, you can compare hyps and refs via multi-bleu.perl.

**Comment by jmuntaner** [comment]
Thanks for the answer!
