### ISSUE TITLE
problem about the rl trainer

### ISSUE THREAD

**Issue by ShuangxiNie** [kh-kim/simple-nmt#4]
i'm confused about the calculation of gradient of rl training(the function _get_gradient in rl_trainer.py).
firstly, in line 77 multiply "-reward" for each sample and in line 79 multiply -1, as a result, we are minimizing the reawrd, but rl is to maximize the total reward.
secondly, this implemention of Minimum Risk Training is not the same as the original paper,  the hyper-parameter \alpha is not considered .

**Comment by kh-kim** [comment]
Hello,

1. Yes. "-reward" leads us to get "risk", and we need to minimize the risk. However, Negative Log Likelihood (NLL) loss tends to maximize log probability via maximizing the equation, thus we multiply -1 to minimize the equation.

2. Yes. I ignore the alpha, but I checked that it is still working.

Thanks.
